### ISSUE TITLE
Crear Front

### ISSUE THREAD

**Issue by zetTtai** [zetTtai/Diversion-con-Colas#17]
Este módulo consistirá en una simple página web que, haciendo peticiones al API_Engine 
muestre el mapa en curso y el estado de los visitantes.

Deberá controlar cualquier aspecto que evite un funcionamiento incorrecto. Así, por 
ejemplo, si cualquier módulo está caído, deberá mostrar un mensaje al respecto.

**Comment by Joselu21** [comment]
Falta la parte de mostrar mensajes si algún módulo no funciona, solo se loguea en consola que se ha producido un error 'X'.
