### ISSUE TITLE
Engine consume la API_REST de OPEN WEATHER 

### ISSUE THREAD

**Issue by zetTtai** [zetTtai/Diversion-con-Colas#23]
1- Consumo de API_rest de un servidor de clima: Adicionalmente a su conexión con el
FWQ_WaitingTimeServer, consumirá el API que ofrece el proveedor de OPEN
WEATHER para obtener el tiempo de 4 ciudades distintas. El alumno deberá elegir
de una lista que creará por si mismo 4 ciudades al azar y, por cada una de ellas, hacer
la llamada al API de OPEN_WEATHER. Nota: En el momento de la corrección, el
profesor podrá solicitar al alumno que añada cualquier ciudad a su criterio. Se asume
que las 4 ciudades consumidas corresponden a las cuatro regiones de 10x10
identificadas en el mapa del resort. Si la temperatura en cualquiera de ellas está por
debajo de 20ºC o por encima de 30º, esa zona del parque quedará bloqueada y sus
atracciones cerradas obligando a redirigir a los visitantes hacia otra atracción.

**Comment by Joselu21** [comment]
Hecho
